[local]
localhost
[mongodb]
localhost
[catalogue]
localhost
[redis]
localhost
[user]
localhost
[cart]
localhost
[shipping]
localhost
[payment]
localhost
[mysql]
localhost
[rabbitmq]
localhost
[frontend]
localhost
